//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTACION
    {
        public short ID_DOCUMENTACION { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string NOMDOCUMENTO { get; set; }
        public byte[] DOCUMENTO { get; set; }
        public short ID_PRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
