//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENCION
    {
        public short ID_MANTENCION { get; set; }
        public string OBSERVACION { get; set; }
        public string GARANTIA { get; set; }
        public Nullable<System.DateTime> FECINGRESO { get; set; }
        public Nullable<System.DateTime> FECSALIDA { get; set; }
        public string ESTADO { get; set; }
        public short ID_SERVICIO { get; set; }
        public short ID_USUARIO { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
