//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterbikeEntities : DbContext
    {
        public MasterbikeEntities()
            : base("name=MasterbikeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DETALLEINGRESO> DETALLEINGRESO { get; set; }
        public DbSet<DETALLEVENTA> DETALLEVENTA { get; set; }
        public DbSet<DOCUMENTACION> DOCUMENTACION { get; set; }
        public DbSet<INGRESO> INGRESO { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<REGERRORES> REGERRORES { get; set; }
        public DbSet<REPORTE> REPORTE { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SEGUIMIENTOENVIOS> SEGUIMIENTOENVIOS { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SOLICITUDARRIENDO> SOLICITUDARRIENDO { get; set; }
        public DbSet<SOLICITUDMANTENCION> SOLICITUDMANTENCION { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    }
}
