//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.INGRESO = new HashSet<INGRESO>();
        }
    
        public short ID_PROVEEDOR { get; set; }
        public string RUT_PROVEEDOR { get; set; }
        public string NOM_PROVEEDOR { get; set; }
        public string APE_PROVEEDOR { get; set; }
        public string DIRECCION_PROVEEDOR { get; set; }
        public Nullable<int> TELEFONO_PROVEEDOR { get; set; }
        public string EMAIL_PROVEEDOR { get; set; }
    
        public virtual ICollection<INGRESO> INGRESO { get; set; }
    }
}
