//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGERRORES
    {
        public short ID_ERROR { get; set; }
        public short CODIGOERROR { get; set; }
        public string MENSAJERROR { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECERROR { get; set; }
    }
}
