//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public short ID_REPORTE { get; set; }
        public string TIPOREPORTE { get; set; }
        public Nullable<System.DateTime> FECINICIO { get; set; }
        public Nullable<System.DateTime> FECFIN { get; set; }
        public System.DateTime FECEMISION { get; set; }
        public string SUCURSALREPORTE { get; set; }
        public Nullable<int> BICICLETAIN { get; set; }
        public Nullable<int> BICICLETAOUT { get; set; }
        public Nullable<int> ACCESORIOIN { get; set; }
        public Nullable<int> ACCESORIOOUT { get; set; }
        public Nullable<int> TOTALVENTA { get; set; }
        public short ID_USUARIO { get; set; }
        public short ID_SUCURSAL { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
