//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID_ROL { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
