//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.MANTENCION = new HashSet<MANTENCION>();
            this.SOLICITUDMANTENCION = new HashSet<SOLICITUDMANTENCION>();
        }
    
        public short ID_SERVICIO { get; set; }
        public string DESCRIPCION_SERVICIO { get; set; }
        public int PRECIOSERVICIO { get; set; }
    
        public virtual ICollection<MANTENCION> MANTENCION { get; set; }
        public virtual ICollection<SOLICITUDMANTENCION> SOLICITUDMANTENCION { get; set; }
    }
}
