//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDARRIENDO
    {
        public short ID_SOL_ARRIENDO { get; set; }
        public string TIPOBICICLETA { get; set; }
        public System.DateTime FECINI_ARRIENDO { get; set; }
        public System.DateTime FECFIN_ARRIENDO { get; set; }
        public string FORMAPAGO_ARRI { get; set; }
        public Nullable<int> DEPOSITOGARANTIA { get; set; }
        public string COMENTARIO { get; set; }
        public short ID_USUARIO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
