//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public SUCURSAL()
        {
            this.REPORTE = new HashSet<REPORTE>();
        }
    
        public short ID_SUCURSAL { get; set; }
        public string NOMSUCURSAL { get; set; }
        public string DIRECCION_SUCURSAL { get; set; }
    
        public virtual ICollection<REPORTE> REPORTE { get; set; }
    }
}
