//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.MANTENCION = new HashSet<MANTENCION>();
            this.REPORTE = new HashSet<REPORTE>();
            this.SOLICITUDARRIENDO = new HashSet<SOLICITUDARRIENDO>();
            this.SOLICITUDMANTENCION = new HashSet<SOLICITUDMANTENCION>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public short ID_USUARIO { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string PNOMBRE { get; set; }
        public string SNOMBRE { get; set; }
        public string APPATERNO { get; set; }
        public string APMATERNO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string RUT_USUARIO { get; set; }
        public Nullable<short> EDAD { get; set; }
        public System.DateTime FECHANAC { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public int NUMTELEFONO { get; set; }
        public string ESTADOCIVIL { get; set; }
        public decimal ID_ROL { get; set; }
    
        public virtual ICollection<MANTENCION> MANTENCION { get; set; }
        public virtual ICollection<REPORTE> REPORTE { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual ICollection<SOLICITUDARRIENDO> SOLICITUDARRIENDO { get; set; }
        public virtual ICollection<SOLICITUDMANTENCION> SOLICITUDMANTENCION { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
