//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masterbike.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
            this.SEGUIMIENTOENVIOS = new HashSet<SEGUIMIENTOENVIOS>();
        }
    
        public short ID_VENTA { get; set; }
        public string TIPOCOMPROBANTE_VENTA { get; set; }
        public int NUMCOMPROBANTE { get; set; }
        public System.DateTime FECHORA { get; set; }
        public short ID_PRODUCTO { get; set; }
        public int TOTALVENTA { get; set; }
        public short ID_USUARIO { get; set; }
    
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ICollection<SEGUIMIENTOENVIOS> SEGUIMIENTOENVIOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
